import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.Properties
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input

plugins {
    id("java")
    application
    id("com.gradleup.shadow") version "9.4.1"
}

group = "su.mtuci"
version = "1.0-SNAPSHOT"

application {
    mainClass = "su.mtuci.Main"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":string-utils"))
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    implementation("ch.qos.logback:logback-classic:1.5.13")
    implementation("org.slf4j:slf4j-api:1.7.25")
}

tasks.test {
    useJUnitPlatform()
}

tasks.shadowJar {
    manifest {
        attributes(Pair("Main-Class", "su.mtuci.Main"))
        }
    }

abstract class PrintInfoTask : DefaultTask() {

    @TaskAction
    fun print() {
        println("======================================")
        println("Это моя первая пользовательская задача!")
        println("Проект: ${project.name}")
        println("Версия Gradle: ${project.gradle.gradleVersion}")
        println("======================================")
        }
    }

tasks.register<PrintInfoTask>("printInfo") {
    group = "Custom"
    description = "Выводит информацию о проекте"
}

abstract class GenerateBuildInfoTask : DefaultTask() {

    @get:Input
    abstract val gitCommitHash: Property<String>

    @TaskAction
    fun generate() {
        val destFile = project.layout.projectDirectory.file("src/main/resources/build-passport.properties").asFile
        destFile.parentFile.mkdirs()

        val previousBuildNumber = if (destFile.exists()) {
            val props = Properties()
            destFile.inputStream().use(props::load)
            props.getProperty("buildNumber")?.toIntOrNull() ?: 0
        } else {
            0
        }

        val nextBuildNumber = previousBuildNumber + 1
        val user = System.getenv("USERNAME") ?: System.getenv("USER") ?: "Unknown User"
        val os = System.getProperty("os.name")
        val javaVersion = System.getProperty("java.version")
        val currentDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))

        destFile.writeText(
            """
            user=$user
            os=$os
            javaVersion=$javaVersion
            buildDate=$currentDate
            gitCommitHash=${gitCommitHash.get()}
            buildNumber=$nextBuildNumber
            welcomeMessage=Welcome to the build! This file is autogenerated.
            """.trimIndent()
        )
    }
}

tasks.register<GenerateBuildInfoTask>("generateBuildInfo") {
    val destFile = layout.projectDirectory.file("src/main/resources/build-passport.properties")
    outputs.file(destFile)
    outputs.upToDateWhen { false }

    gitCommitHash.set(
        providers.exec {
            commandLine("git", "rev-parse", "--short", "HEAD")
            isIgnoreExitValue = true
        }.standardOutput.asText.map { output ->
            output.trim().ifEmpty { "unknown" }
        }
    )
}

tasks.named("processResources") {
    dependsOn(tasks.named("generateBuildInfo"))
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}