spring.application.name=spring-lab3-notifications

# Адрес подключения к БД (значение подставляется из переменной окружения DB_URL)
spring.datasource.url=${DB_URL}

# Имя пользователя PostgreSQL (из переменной DB_USERNAME)
spring.datasource.username=${DB_USERNAME}

# Пароль пользователя БД (из переменной DB_PASSWORD)
spring.datasource.password=${DB_PASSWORD}

# update: Hibernate сам создаёт/обновляет таблицы на основе сущностей
spring.jpa.hibernate.ddl-auto=update

# Вывод SQL в консоль (удобно для отладки)
spring.jpa.show-sql=true

# Красивый вывод SQL с отступами
spring.jpa.properties.hibernate.format_sql=true